name: IU Workbook Bibliography
description: Create your IU Workbook bibliography with GitHub Actions.

inputs:
  # content details
  bibliography:
    description: Path to bibliography.md
    required: true
    
  # configuration details
  format_doc:
    description: Path to the Microsoft Word template of the bibliography
    required: true
    
runs:
  using: "composite"
  steps:
    - name: List Directory
      shell: bash
      run: ls -R
    - name: Create Bibliography
      uses: docker://pandoc/core:2.9
      with:
        args: >-
          -t docx
          -f markdown
          --reference-doc=${{ inputs.format_doc }}
          --output=bibliography.docx
          ${{ inputs.bibliography }}
    - name: Convert Bibliography to PDF
      run: |
        sudo apt-get install unoconv -y  # Convert .docx to .pdf
        unoconv bibliography.docx
      shell: bash
    - name: Upload PDF to GitHub Artifacts
      uses: actions/upload-artifact@master
      with:
        name: bibliography
        path: bibliography.pdf
